### ISSUE TITLE
Fade color

### ISSUE THREAD

**Issue by MinaSamirCap** [bosphere/Android-FadingEdgeLayout#2]
Can I change the fade color ..??

**Comment by bosphere** [comment]
The fading edges are not implemented as color overlay but rather linear gradient alpha mask of the content. So it'll naturally follow the color of the background.

**Comment by MinaSamirCap** [comment]
that means I can not have different colors for the background and the fading color
the fading color will follow the background color only...

**Comment by bosphere** [comment]
No you cannot have different colors because the fading edge is not made by drawing an overlay on top of the content. Intead it makes the content transparent to appear as if there is a fading edge.

**Comment by MinaSamirCap** [comment]
okay thanks
